# Generated by Django 4.2.5 on 2023-10-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=30, verbose_name="队伍名"),
                ),
                ("introduction", models.TextField(blank=True, verbose_name="队伍口号")),
                (
                    "score",
                    models.IntegerField(blank=True, default=0, verbose_name="得分"),
                ),
                (
                    "task",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teams",
                        to="tasks.task",
                        verbose_name="完成的任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "队伍",
                "verbose_name_plural": "队伍",
                "db_table": "zq_match_team",
            },
        ),
    ]
