# Generated by Django 5.2.8 on 2025-11-19 11:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academies', '0003_update_academies_data'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='用户名')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(default='', max_length=13, verbose_name='手机')),
                ('qq', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='QQ')),
                ('wechat', models.CharField(default='', max_length=25, verbose_name='wechat')),
                ('school_number', models.CharField(default='', max_length=20, verbose_name='学号')),
                ('avatar', models.ImageField(default='avatar\\default.jpg', upload_to='avatar', verbose_name='头像')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('grade', models.IntegerField(default=0, verbose_name='年级')),
                ('interest', models.TextField(default='', max_length=500, verbose_name='爱好')),
                ('major_category', models.CharField(blank=True, default='', max_length=50, verbose_name='专业大类')),
                ('is_match', models.BooleanField(default=False, verbose_name='是否匹配')),
                ('is_authenticated', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理员')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='超级用户')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='密码')),
                ('openid', models.CharField(max_length=64, null=True, unique=True, verbose_name='微信openid')),
                ('union_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='自强union_id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academy_users', to='academies.academy', verbose_name='院系')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('people', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='以前匹配过的用户们')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='teams.team', verbose_name='队伍')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'zq_match_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
