# Generated by Django 4.2.6 on 2023-10-23 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_matched"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_matched",
        ),
        migrations.AddField(
            model_name="user",
            name="is_match",
            field=models.BooleanField(default=False, verbose_name="是否匹配"),
        ),
        migrations.AddField(
            model_name="user",
            name="people",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="以前匹配过的用户们"
            ),
        ),
    ]
