# Generated by Django 4.2.6 on 2025-10-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_matched_user_is_match_user_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='application',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='QQ'),
        ),
    ]
