# Generated by Django 4.2.6 on 2025-10-29 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_interest_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.TextField(default='', max_length=500, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='user',
            name='union_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='自强union_id'),
        ),
    ]
