# Generated by Django 4.2.5 on 2023-10-14 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=50, verbose_name="打卡标题"),
                ),
                ("description", models.TextField(blank=True, verbose_name="打卡内容描述")),
                (
                    "photo",
                    models.ImageField(upload_to="post\\photo", verbose_name="打卡配图"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="tasks.task",
                        verbose_name="对应的任务",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="teams.team",
                        verbose_name="所属队伍",
                    ),
                ),
            ],
            options={
                "verbose_name": "打卡",
                "verbose_name_plural": "打卡",
                "db_table": "zq_match_post",
            },
        ),
    ]
