# Generated by Django 4.2.5 on 2023-10-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_choice",
                    models.IntegerField(
                        choices=[
                            (0, "文学院"),
                            (1, "历史学院"),
                            (2, "哲学学院"),
                            (3, "外国语言文学学院"),
                            (4, "新闻与传播学院"),
                            (5, "艺术学院"),
                            (6, "信息管理学院"),
                            (7, "经济与管理学院"),
                            (8, "法学院"),
                            (9, "政治与公共管理学院"),
                            (10, "马克思主义学院"),
                            (11, "社会学院"),
                            (12, "数学与统计学院"),
                            (13, "物理与科学技术学院"),
                            (14, "化学与分子科学学院"),
                            (15, "生命科学学院"),
                            (16, "水利水电学院"),
                            (17, "电气与自动化学院"),
                            (18, "动力与机械学院"),
                            (19, "城市设计学院"),
                            (20, "土木建筑工程学院"),
                            (21, "计算机学院"),
                            (22, "电子信息学院"),
                            (23, "遥感信息工程学院"),
                            (24, "国家网络安全学院"),
                            (25, "测绘学院"),
                            (26, "资源与环境科学学院"),
                            (27, "泰康医学院（基础医学院）"),
                            (28, "口腔医学院"),
                            (29, "药学院"),
                            (30, "公共卫生学院"),
                            (31, "护理学院"),
                            (32, "第一临床医学院"),
                            (33, "第二临床医学院"),
                            (34, "弘毅学堂"),
                        ],
                        verbose_name="第一专业意向",
                    ),
                ),
                (
                    "second_choice",
                    models.IntegerField(
                        choices=[
                            (0, "文学院"),
                            (1, "历史学院"),
                            (2, "哲学学院"),
                            (3, "外国语言文学学院"),
                            (4, "新闻与传播学院"),
                            (5, "艺术学院"),
                            (6, "信息管理学院"),
                            (7, "经济与管理学院"),
                            (8, "法学院"),
                            (9, "政治与公共管理学院"),
                            (10, "马克思主义学院"),
                            (11, "社会学院"),
                            (12, "数学与统计学院"),
                            (13, "物理与科学技术学院"),
                            (14, "化学与分子科学学院"),
                            (15, "生命科学学院"),
                            (16, "水利水电学院"),
                            (17, "电气与自动化学院"),
                            (18, "动力与机械学院"),
                            (19, "城市设计学院"),
                            (20, "土木建筑工程学院"),
                            (21, "计算机学院"),
                            (22, "电子信息学院"),
                            (23, "遥感信息工程学院"),
                            (24, "国家网络安全学院"),
                            (25, "测绘学院"),
                            (26, "资源与环境科学学院"),
                            (27, "泰康医学院（基础医学院）"),
                            (28, "口腔医学院"),
                            (29, "药学院"),
                            (30, "公共卫生学院"),
                            (31, "护理学院"),
                            (32, "第一临床医学院"),
                            (33, "第二临床医学院"),
                            (34, "弘毅学堂"),
                        ],
                        verbose_name="第二专业意向",
                    ),
                ),
                (
                    "is_fuzzy",
                    models.BooleanField(
                        choices=[(False, "否"), (True, "是")],
                        default=False,
                        verbose_name="是否模糊匹配",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("none", "无"), ("male", "男"), ("female", "女")],
                        max_length=6,
                        verbose_name="选择同伴性别",
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="手机号码")),
                ("qq", models.CharField(max_length=11, verbose_name="qq号码")),
            ],
            options={
                "verbose_name": "报名表",
                "verbose_name_plural": "报名表",
                "db_table": "zq_match_applications",
            },
        ),
    ]
