# Generated by Django 4.2.5 on 2023-10-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0002_data_initial"),
        ("applications", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="first_choice",
        ),
        migrations.RemoveField(
            model_name="application",
            name="is_fuzzy",
        ),
        migrations.RemoveField(
            model_name="application",
            name="second_choice",
        ),
        migrations.AddField(
            model_name="application",
            name="academy_choices",
            field=models.ManyToManyField(
                blank=True,
                related_name="applications",
                to="academies.academy",
                verbose_name="愿意交换的专业",
            ),
        ),
    ]
