# Generated by Django 4.2.6 on 2023-10-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0002_data_initial"),
        ("applications", "0003_remove_application_first_choice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="academy_choices",
        ),
        migrations.RemoveField(
            model_name="application",
            name="gender",
        ),
        migrations.AddField(
            model_name="application",
            name="academy_choice",
            field=models.ManyToManyField(
                null=True,
                related_name="applications",
                to="academies.academy",
                verbose_name="愿意交换的专业",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="gender_choice",
            field=models.CharField(default="无", max_length=3, verbose_name="选择同伴性别"),
        ),
        migrations.AddField(
            model_name="application",
            name="my_academy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academies.academy",
                verbose_name="我的专业",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="my_gender",
            field=models.CharField(default="无", max_length=3, verbose_name="我的性别"),
        ),
    ]
