# Generated by Django 4.2.6 on 2025-10-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0002_data_initial'),
        ('applications', '0004_remove_application_academy_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='academy_choice',
            field=models.ManyToManyField(related_name='applications', to='academies.academy', verbose_name='愿意交换的专业'),
        ),
    ]
