# Generated by Django 4.2.6 on 2025-10-30 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0005_alter_application_academy_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_attempts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '匹配尝试',
                'verbose_name_plural': '匹配尝试',
                'db_table': 'zq_match_attempt',
                'indexes': [models.Index(fields=['user', 'created_at'], name='zq_match_at_user_id_b74fcd_idx')],
            },
        ),
    ]
