# Generated by Django 5.2.8 on 2025-11-20 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_teaminvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已同意'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='申请状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '换队友申请',
                'verbose_name_plural': '换队友申请',
                'db_table': 'zq_match_team_exchange_request',
            },
        ),
        migrations.RenameIndex(
            model_name='teaminvitation',
            new_name='zq_match_te_invitee_975bfc_idx',
            old_name='zq_match_te_invitee__idx',
        ),
        migrations.RenameIndex(
            model_name='teaminvitation',
            new_name='zq_match_te_inviter_f9c608_idx',
            old_name='zq_match_te_inviter__idx',
        ),
        migrations.AddField(
            model_name='teamexchangerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_exchange_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请方'),
        ),
        migrations.AddField(
            model_name='teamexchangerequest',
            name='teammate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_exchange_requests', to=settings.AUTH_USER_MODEL, verbose_name='队友'),
        ),
        migrations.AddIndex(
            model_name='teamexchangerequest',
            index=models.Index(fields=['teammate', 'status'], name='zq_match_te_teammat_671414_idx'),
        ),
        migrations.AddIndex(
            model_name='teamexchangerequest',
            index=models.Index(fields=['requester', 'status'], name='zq_match_te_request_e89558_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamexchangerequest',
            unique_together={('requester', 'teammate')},
        ),
    ]
