# Generated by Django 4.2.5 on 2023-10-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=50, verbose_name="任务名"),
                ),
                (
                    "cover",
                    models.ImageField(upload_to="task\\cover", verbose_name="封面"),
                ),
                ("introduction", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "score",
                    models.IntegerField(blank=True, default=100, verbose_name="任务分数"),
                ),
                ("start_time", models.DateField(verbose_name="开始时间")),
                ("end_time", models.DateField(verbose_name="结束时间")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "打卡任务",
                "verbose_name_plural": "打卡任务",
                "db_table": "zq_match_tasks",
            },
        ),
    ]
